"""HTTP API for local audio generation.

Endpoint map:
  GET    /health                  liveness + device + provider readiness
  GET    /v1/models               what can generate what, with licences and params
  POST   /v1/audio/speech         TTS; waits inline (seconds) then returns audio_url
  POST   /v1/audio/music          enqueues; returns a job to poll (minutes)
  POST   /v1/audio/sfx            enqueues; returns a job to poll
  GET    /v1/jobs, /v1/jobs/{id}  job status; DELETE cancels a queued job
  GET    /v1/audio/{id}           the generated bytes; DELETE removes them
  GET/POST/DELETE /v1/voices      voice-clone reference samples
  GET    /v1/storage              disk usage
"""
from __future__ import annotations

import asyncio
import contextlib
import logging
import math

from fastapi import FastAPI, File, Form, HTTPException, Query, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse

from . import storage
from .auth import api_key_middleware
from .config import get_settings
from .jobs import Job, JobQueue, JobStatus
from .providers.base import Capability, GenerateRequest, check_audio_sane
from .registry import get_registry
from .schemas import GenerateBody, SpeechBody

settings = get_settings()
logging.basicConfig(
    level=settings.log_level,
    format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
)
log = logging.getLogger("audiogen")

queue = JobQueue(max_concurrent=settings.max_concurrent_jobs)

# TTS is quick, so the client waits inline rather than polling. Past this the
# request returns a job id instead of blocking a proxy connection forever.
SPEECH_INLINE_WAIT = 180.0


@contextlib.asynccontextmanager
async def lifespan(app: FastAPI):
    reg = get_registry()
    log.info("device=%s providers=%d available=%d",
             settings.device, len(reg.all()), sum(p.available() for p in reg.all()))
    sweeper = asyncio.create_task(_sweep_idle_models())
    try:
        yield
    finally:
        sweeper.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await sweeper


async def _sweep_idle_models() -> None:
    """Return VRAM when a model has gone unused. Matters on a shared GPU."""
    timeout = settings.model_idle_timeout
    if timeout <= 0:
        return
    while True:
        await asyncio.sleep(max(30, timeout // 4))
        try:
            get_registry().sweep_idle(timeout)
        except Exception:                              # noqa: BLE001
            log.exception("idle sweep failed")


app = FastAPI(
    title="Audio Performance Generator API",
    version="0.1.0",
    lifespan=lifespan,
)
app.middleware("http")(api_key_middleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


def _gpu_info() -> dict | None:
    try:
        import torch
        if not torch.cuda.is_available():
            return None
        free, total = torch.cuda.mem_get_info()
        return {
            "name": torch.cuda.get_device_name(0),
            "vram_total_gb": round(total / 1024**3, 2),
            "vram_free_gb": round(free / 1024**3, 2),
        }
    except Exception:                                  # noqa: BLE001
        return None


@app.get("/health")
def health():
    reg = get_registry()
    providers = reg.all()
    available = sum(p.available() for p in providers)
    return {
        "status": "ok" if available else "degraded",
        "device": settings.device,
        "providers_available": available,
        "providers_total": len(providers),
        "gpu": _gpu_info(),
        "jobs": queue.stats(),
    }


@app.get("/v1/models")
def list_models():
    """Everything the UI needs to render its controls without hardcoding."""
    reg = get_registry()
    return {
        "device": settings.device,
        "providers": [p.info() for p in reg.all()],
        "defaults": {
            cap.value: (reg.default_for(cap).id if reg.default_for(cap) else None)
            for cap in Capability
        },
    }


def _run_generation(provider, req: GenerateRequest, kind: str):
    """Build the thread-side callable the job queue will execute."""
    def _work(job: Job) -> dict:
        job.message = f"generating with {provider.id}"
        # Held for the whole generation so the idle sweeper cannot unload the
        # model while this job is still running on it.
        with provider.in_use():
            result = provider.generate(req)

        # Fail loudly on silent/degenerate output rather than storing a clip of
        # nothing and reporting success. Only meaningful for WAV; the cloud
        # providers return mp3 and are skipped.
        if result.mime == "audio/wav":
            check_audio_sane(result.audio)

        audio_id = storage.save_audio(
            result.audio,
            suffix=".mp3" if result.mime == "audio/mpeg" else ".wav",
            meta={
                "kind": kind,
                "provider": result.provider_id,
                "prompt": req.prompt[:500],
                "sample_rate": result.sample_rate,
                "duration": result.duration,
                "mime": result.mime,
            },
        )
        return {
            "audio_id": audio_id,
            "meta": {
                "duration": result.duration,
                "sample_rate": result.sample_rate,
                "mime": result.mime,
                "provider": result.provider_id,
            },
        }
    return _work


def _resolve(capability: Capability, provider_id: str | None):
    reg = get_registry()
    try:
        return reg.resolve(capability, provider_id)
    except KeyError as exc:
        raise HTTPException(404, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    except RuntimeError as exc:
        raise HTTPException(503, str(exc)) from exc


def _validated_seconds(provider, seconds: float | None, params: dict) -> float | None:
    """Check a requested duration against the resolved provider's own bounds.

    Providers advertise a `seconds` param with a range. When one does, the
    request must fall inside it -- a clearer failure than a job that dies later
    inside the model or the cloud API. When a provider advertises no duration
    at all (TTS length follows the text), the value is dropped rather than
    passed on: code that never declared a bound must not receive an unbounded
    number. Both the top-level field and params["seconds"] are covered, since
    providers read either.
    """
    raw = seconds if seconds is not None else params.get("seconds")
    spec = next((p for p in provider.params() if p.name == "seconds"), None)
    if spec is None:
        params.pop("seconds", None)
        return None
    if raw is None:
        return None
    try:
        value = float(raw)
    except (TypeError, ValueError):
        raise HTTPException(422, f"seconds must be a number, got {raw!r}") from None
    lo, hi = spec.minimum, spec.maximum
    if not math.isfinite(value) or (lo is not None and value < lo) or (hi is not None and value > hi):
        span = f"{lo:g}-{hi:g}" if lo is not None and hi is not None else (
            f">= {lo:g}" if lo is not None else f"<= {hi:g}")
        raise HTTPException(422, f"seconds must be {span} for {provider.id} (got {raw})")
    params["seconds"] = value
    return value


def _job_payload(job: Job) -> dict:
    payload = job.public()
    payload["audio_url"] = f"/v1/audio/{job.audio_id}" if job.audio_id else None
    return payload


@app.post("/v1/audio/speech")
async def generate_speech(body: SpeechBody, wait: bool = Query(True)):
    prompt = body.resolved_prompt()
    if not prompt or not prompt.strip():
        raise HTTPException(422, "prompt/input is empty")

    provider = _resolve(Capability.VOICE, body.provider)
    params = dict(body.params)
    seconds = _validated_seconds(provider, body.seconds, params)
    req = GenerateRequest(
        prompt=prompt,
        capability=Capability.VOICE,
        voice_id=body.resolved_voice(),
        seconds=seconds,
        seed=body.seed,
        params=params,
    )
    job = queue.submit("speech", _run_generation(provider, req, "voice"),
                       meta={"provider": provider.id})
    if wait:
        await queue.wait_for(job, timeout=SPEECH_INLINE_WAIT)
        if job.status is JobStatus.ERROR:
            raise HTTPException(500, job.error or "generation failed")
    return JSONResponse(_job_payload(job), status_code=200 if job.audio_id else 202)


async def _enqueue(capability: Capability, body: GenerateBody, kind: str):
    provider = _resolve(capability, body.provider)
    params = dict(body.params)
    seconds = _validated_seconds(provider, body.seconds, params)
    req = GenerateRequest(
        prompt=body.prompt,
        capability=capability,
        voice_id=body.voice_id,
        seconds=seconds,
        seed=body.seed,
        params=params,
    )
    job = queue.submit(kind, _run_generation(provider, req, kind), meta={"provider": provider.id})
    return JSONResponse(_job_payload(job), status_code=202)


@app.post("/v1/audio/music")
async def generate_music(body: GenerateBody):
    return await _enqueue(Capability.MUSIC, body, "music")


@app.post("/v1/audio/sfx")
async def generate_sfx(body: GenerateBody):
    return await _enqueue(Capability.SFX, body, "sfx")


@app.get("/v1/jobs")
def list_jobs(limit: int = Query(50, ge=1, le=200)):
    # Same shape as GET /v1/jobs/{id}, including audio_url, so a listed job
    # can be recovered without a second request.
    return {"jobs": [
        {**j, "audio_url": f"/v1/audio/{j['audio_id']}" if j.get("audio_id") else None}
        for j in queue.list(limit)
    ]}


@app.get("/v1/jobs/{job_id}")
def get_job(job_id: str):
    job = queue.get(job_id)
    if job is None:
        raise HTTPException(404, "unknown job")
    return _job_payload(job)


@app.delete("/v1/jobs/{job_id}")
def cancel_job(job_id: str):
    job = queue.get(job_id)
    if job is None:
        raise HTTPException(404, "unknown job")
    cancelled = queue.cancel(job_id)
    if not cancelled:
        # Be honest: work already inside torch cannot be interrupted.
        raise HTTPException(409, f"job is {job.status.value} and can no longer be cancelled")
    return _job_payload(job)


@app.get("/v1/audio/{audio_id}")
def get_audio(audio_id: str):
    try:
        path = storage.audio_path(audio_id)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    if path is None:
        raise HTTPException(404, "unknown audio id")
    meta = storage.audio_meta(audio_id) or {}
    return FileResponse(
        path,
        media_type=meta.get("mime", "audio/wav"),
        headers={"Cache-Control": "public, max-age=31536000, immutable"},
    )


@app.delete("/v1/audio/{audio_id}")
def remove_audio(audio_id: str):
    try:
        ok = storage.delete_audio(audio_id)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    if not ok:
        raise HTTPException(404, "unknown audio id")
    return {"deleted": audio_id}


@app.get("/v1/voices")
def list_voices():
    return {"voices": storage.list_voice_references()}


@app.post("/v1/voices")
async def add_voice(file: UploadFile = File(...), name: str = Form("")):
    """Upload a reference sample for zero-shot voice cloning.

    Consent is the user's responsibility: cloning a real person's voice without
    their permission is unlawful in a growing number of jurisdictions.
    """
    data = await file.read()
    if not data:
        raise HTTPException(422, "empty upload")
    if len(data) > 25 * 1024 * 1024:
        raise HTTPException(413, "reference sample too large (max 25 MB)")
    suffix = "." + (file.filename or "ref.wav").rsplit(".", 1)[-1].lower()
    if suffix not in {".wav", ".mp3", ".flac", ".ogg", ".m4a"}:
        raise HTTPException(415, f"unsupported audio type: {suffix}")
    return storage.save_voice_reference(data, name or (file.filename or "Reference"), suffix=suffix)


@app.delete("/v1/voices/{voice_id}")
def remove_voice(voice_id: str):
    try:
        ok = storage.delete_voice_reference(voice_id)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    if not ok:
        raise HTTPException(404, "unknown voice id")
    return {"deleted": voice_id}


@app.get("/v1/storage")
def storage_usage():
    return storage.usage()
